server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: *
    password: *
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
    config:
      import: configserver:http://localhost:9296
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://dev-78713843.okta.com/oauth2/default
        client:
          registration:
            internal-client:
              provider: okta
              authorization-grant-type: client_credentials
              scope: internal
              client-id: 0oacs6uqk7CtoaNh35d7
              client-secret: JZ7k4xnggNh10H8XCDI2BYXEBkIcazdwAVfXrW5TDhr8z0YJBxBSi_d6cFc8M01a
          provider:
            okta:
              issuer-uri: https://dev-78713843.okta.com/oauth2/default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        slidingWindowType: COUNT_BASED

microservices:
  product: http://product-service-svc/product
  payment: http://product-service-svc/payment

