server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: *
    password: *
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
    config:
      import: configserver:http://localhost:9296

  #eureka:
    #instance:
    # prefer-ip-address: true
    #client:
    #fetch-registry: true
    #register-with-eureka: true
      #service-url:
      #defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

